### Listar usuários
GET http://localhost:8080/users

### Buscar usuário por ID
GET http://localhost:8080/users/5724bff6-c06f-43b1-8bf6-360eb487aea8

### Cadastrar usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "João",
  "email": "luan@gmail.com",
  "cpf": "",
  "password": null,
  "address": {
    "zipCode": "12345678",
    "street": "Test",
    "city": "Test",
    "state": "Test",
    "number": "123",
    "complement": null
  },
  "primaryPhone": null,
  "secondaryPhone": null
}

### Alterar usuário
PUT http://localhost:8080/users/3533bf47-9b5a-4877-8dc1-12cb536280c3
Content-Type: application/json

{
  "name": "João",
  "email": "joão@gmail.com",
  "cpf": "298.631.820-79",
  "password": "123",
  "address": {
    "zipCode": "68908-192",
    "street": "Passagem Santa Luzia",
    "city": "Macapá",
    "state": "AP",
    "number": "18",
    "complement": null
  },
  "primaryPhone": "(96) 3895-7144",
  "secondaryPhone": "(96) 98763-2104"
}

### Listar revisões
GET http://localhost:8080/users/868046dd-68d6-49b5-a462-471e31ad386a/revisions

### Comparar revisões
GET http://localhost:8080/users/868046dd-68d6-49b5-a462-471e31ad386a/revisions/1/compare
